### ISSUE TITLE
请问是只读取了x y z 三个坐标吗？ 

### ISSUE THREAD

**Issue by Barcelona16** [MilesChing/TubeTK-tre2matrix#1]
除了x y z r 之外的其他参数不需要考虑吗
另外我正在配TubeTK的环境 你之前有配过吗

**Comment by MilesChing** [comment]
我对这个文件的结构也不是特别理解，官方似乎没有解释文档，但是有x、y、z、r已经足够还原为体素格式了。TubeTK的环境我们还没有无错地配出来。

**Comment by Barcelona16** [comment]
> 我对这个文件的结构也不是特别理解，官方似乎没有解释文档，但是有x、y、z、r已经足够还原为体素格式了。TubeTK的环境我们还没有无错地配出来。

我之前问了TubeTK的人，ITK也是可以读取.tre的，但是格式转换的话只有TubeTK有接口。
另外问一下还原为体素格式是怎么做的呢，r是中心线半径的话是统计在中心线半径内的体素为1么？
我目前用的是别人做了一些预处理的tre作为ground true，如果想把tre文件建模的话有什么好的方法吗？

**Comment by MilesChing** [comment]
@Barcelona16 这份代码里面用的是非常简单的认为血管由圆柱体组成，r是前一段或后一段中心线的半径。我按照数据集说明里给出的像素数统计了圆柱里面的像素，这样做是可以还原出一个结构的，不过可能不太精确。

你可以用某种插值方法计算中心线上每个点处的柱形半径，另外如果能让TubeTK那边说明一下这个格式的具体定义就更方便了。我们现在只是猜测除了x、y、z、r以外的是一些TubeTK内部用到的Flag，似乎与重建血管结构关系不大。

**Comment by Barcelona16** [comment]
@MilesChing 
这种格式在itksoftwareguide里面描述的是算作 spatial object，文件内的参数有一些在itk的wiki上面有介绍，我后来找到了别人用TubeTK处理过的文件就没再去研究了，也许对你有帮助。

**Comment by MilesChing** [comment]
@Barcelona16  好的，有时间我去看一下。请问你使用的预处理过的数据集是公开的吗，可以提供一下链接吗？

**Comment by Barcelona16** [comment]
@MilesChing  我发到你邮件上吧 是公开的
